### PR TITLE
Modernize the library

### PR DESCRIPTION
**Pull request by d4rky-pl**
- update babel to 7.0
- add Rollup for bundle compilation
- move external dependencies to peerDependencies
- replace require() calls with import/export syntax
- inline necessary lodash parts to remove entire library as hard dependency
- bump version to 0.2.2

Final package size reduced from

```
npm notice package size:  1.5 MB
npm notice unpacked size: 1.8 MB
```

to

```
npm notice package size:  119.4 kB
npm notice unpacked size: 523.1 kB
```

### CODE REVIEW

**Comment by d4rky-pl** [comment]
Sure, I was considering waiting for #80 to merge before sending this but decided it makes sense to just push it. 
RIght now I'm at work so I'm afraid this will have to wait few more hours though.

**Comment by d4rky-pl** [comment]
Do you think all these changes merit a 0.3.0 release or only 0.2.2 ?

**Comment by Yomguithereal** [comment]
`0.3.0` I guess since there is a new feature.

**Comment by d4rky-pl** [comment]
All right, master have been merged in and I bumped the version to 0.3.0. Tested the library working both with `run.js demo` and with an example app

**Comment by Yomguithereal** [comment]
I'll merge then. Do you need a swift npm release?

**Comment by Yomguithereal** [comment]
When I run the demo I get this:

```
WARNING: the `ws` package must be installed to use `react-devtools`.
```

**Comment by d4rky-pl** [comment]
Yeah, devtools and ws have been moved as peerdependencies. We may also add it as devdependency so the warning is not visible in demo or we can hide/remove the warning since even you yourself tripped over the fact this warning is visible only when NODE_ENV is not set to "production" ;)

**Comment by Yomguithereal** [comment]
Anyway, v0.3.0 is live on npm :)

**Pull request merged**
