### PR TITLE
update react support, context & hooks

### PR DESCRIPTION
**Pull request by konsumer**
This will add support for context & hooks, and update the fiber implementation. Related to #88 .

* [X] - update react fiber to handle new API, with `@next` react and not error
* [X] - demo for context
* [X] - demo for hooks

### CODE REVIEW

**Comment by konsumer** [comment]
It's not required for context, but hooks are only available in `@next` (currently `16.7.0-alpha.2`.)

I could go to `16.6.3` (current `@latest`) and just have hooks demo not work (but hooks will be fine in user's code.)

**Comment by Yomguithereal** [comment]
Ok. Can I be a bit annoying and ask you to split this PR into two: one for context, and a second one for hooks, please?

> I could go to 16.6.3 (current @latest) and just have hooks demo not work (but hooks will be fine in user's code.)

I could live with that I think. Then we'll need to update the dev deps when react officially moves hooks to latest. Does it seem good to you?

**Comment by konsumer** [comment]
> Can I be a bit annoying and ask you to split this PR into two: one for context, and a second one for hooks, please?

I'm not sure how to do do that. Do you mean rewrite the code changes as different commits?

> Then we'll need to update the dev deps when react officially moves hooks to latest. Does it seem good to you?

sounds perfect. I'll make the change and add a note to the hook demo that it won't work with older versions of react.

**Comment by konsumer** [comment]
> ask you to split this PR into two: one for context, and a second one for hooks

More about this: this PR is mostly not directly related to hooks or context (I just made demos for those.) This PR is primarily an update of react & react-reconciler, and rewriting the fiber part to follow the current react-reconciler API.

**Comment by konsumer** [comment]
As a sidenote, I set peer-dep to `16.6.3`, but left dev-dep at `16.7.0-alpha.2`, so people can run the hook example, but won't be warned to use alpha, if they import it. I'm happy to set it however you want, but this seems like a good plan to me.

**Comment by Yomguithereal** [comment]
Ok, I'll wait just a little bit to see if anybody interested in the repo has some remarks then I will merge & release. Ping me if I forget.

**Comment by konsumer** [comment]
Hi, not sure if I am giving it enough time, but this is me pinging 😃

I have been using the fork in [this project](https://github.com/konsumer/keybase-cli) and it seems to be working well, but if there are more thorough tests I should put it through (other than the examples) let me know.

**Comment by Yomguithereal** [comment]
v0.5.0 released with your changes.

**Pull request merged**
