### PR TITLE
Fix issue when updating data or rows properties

### PR DESCRIPTION
**Pull request by esnunes**
In order to update data or rows properties of Table and ListTable the method setData must be called.

### CODE REVIEW

**Comment by Yomguithereal** [comment]
Hello @esnunes. Thanks for this sensible fix. Can you affirm that the `rows` and `data` properties are not used differently by some other widgets?

**Comment by esnunes** [comment]
Hi @Yomguithereal ,

Based in [blessed](https://github.com/chjj/blessed) documentation there is a `rows` in node element and `data` also. To better handle this and avoid surprises I'm considering check if the node has `setData` method before call it, what do you think? In case you agree I will change both PR.

```js
    // Table and ListTable data / rows
    else if ((key === 'data' || key === 'rows') && node.setData)
      node.setData(value);
```

**Comment by Yomguithereal** [comment]
This seems to do the trick @esnunes. Let us go this way!

**Comment by esnunes** [comment]
Thanks @Yomguithereal , I've updated both PR.

**Comment by Yomguithereal** [comment]
Thanks @esnunes. Merging your PR right now and releasing a new version with your fixes.

**Comment by Yomguithereal** [comment]
`0.1.5` is now live. Thanks @esnunes.

**Comment by esnunes** [comment]
Thanks @Yomguithereal !

**Pull request merged**
