### PR TITLE
invariant from npm and fix clone url

### PR DESCRIPTION
**Pull request by vicentedealencar**
I had to make this to go through the demo, so here is the PR

### CODE REVIEW

**Comment by Yomguithereal** [comment]
Hello @vicentedealencar. Why didn't the ssh git clone work on your side? And can you tell me what react version was installed that did not provide you with the `invariant` module please?

**Comment by vicentedealencar** [comment]
Not sure if clone doesn`t work because of windows. Anyway, I think browser-like urls are more friendly.

```
C:\Temp> git clone git@github.com:Yomguithereal/react-blessed.git
Cloning into 'react-blessed'...
The authenticity of host 'github.com (192.30.252.128)' can't be established.
RSA key fingerprint is 16:27:ac:a5:76:28:2d:36:63:1b:56:4d:eb:df:a6:48.
Are you sure you want to continue connecting (yes/no)? yes
Warning: Permanently added 'github.com,192.30.252.128' (RSA) to the list of known hosts.
Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```

react@0.14.0-beta3 throws Error: Cannot find module 'react/lib/invariant', currently on 0.14.0-beta1

this repo excites me, thank you

**Comment by Yomguithereal** [comment]
Ok. I'll check the latest react beta and fix this.

**Comment by Yomguithereal** [comment]
So Facebook replaced React's internal invariant by `fbjs/lib/invariant`. Let me merge your PR then :).

**Pull request merged**
